#!/usr/bin/env python3
"""Stamp a "Related guides" section into every hand-made guide page.

Relations are derived from the same menu data stamp_nav.py maintains:
  - class spec pages   -> the class's other two specs, the class hub, the BiS browser
  - profession pages   -> complementary professions (mining -> blacksmithing, ...), hub
  - speed-route pages  -> previous/next bracket, methods comparison, hub
  - comparison pages   -> the other comparisons, hub
  - hub pages          -> the other hubs
Special-layout pages (index, bis.html, newcontent.html, wow-camelot.html) are skipped;
generated pages (bis-*.html, news-*.html) already carry their own sibling links.

Idempotent: the block lives between sentinel comments and is replaced in place;
first run inserts it right before the page footer. Styling lives in assets/site.css
(.related-guides). Usage: python3 tools/related_guides.py
"""

import re
import sys
import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

spec = importlib.util.spec_from_file_location("stamp_nav", ROOT / "tools" / "stamp_nav.py")
stamp_nav = importlib.util.module_from_spec(spec)
spec.loader.exec_module(stamp_nav)
CLASSES, LEVELING, PROFESSIONS = stamp_nav.CLASSES, stamp_nav.LEVELING, stamp_nav.PROFESSIONS

REL_START = "<!-- related:start (generated by tools/related_guides.py — do not edit by hand) -->"
REL_END = "<!-- related:end -->"

SKIP = {"index.html", "bis.html", "newcontent.html", "wow-camelot.html"}

# profession -> complementary professions (order = display order)
PROF_PAIRS = {
    "alchemy": ["herbalism", "fishing"],
    "blacksmithing": ["mining", "engineering"],
    "enchanting": ["tailoring", "jewelcrafting"],
    "engineering": ["mining", "blacksmithing"],
    "inscription": ["herbalism", "alchemy"],
    "jewelcrafting": ["mining", "enchanting"],
    "leatherworking": ["skinning", "first-aid"],
    "tailoring": ["enchanting", "first-aid"],
    "herbalism": ["alchemy", "inscription"],
    "mining": ["blacksmithing", "engineering", "jewelcrafting"],
    "skinning": ["leatherworking", "cooking"],
    "cooking": ["fishing", "first-aid"],
    "first-aid": ["cooking", "fishing"],
    "fishing": ["cooking", "alchemy"],
}

HUBS = [
    ("class-guides.html", "All class guides", "Overview"),
    ("fast-leveling.html", "Speed leveling", "Overview"),
    ("professions.html", "All professions", "Overview"),
    ("bis.html", "BiS list browser", "Gear"),
]


def build_relations():
    """page filename -> list of (kicker, title, href)"""
    rel = {}

    prof_titles = {}
    for _group, entries in PROFESSIONS:
        for title, page in entries:
            prof_titles[page.replace(".html", "")] = (title, page)

    # class spec pages
    for cls, specs in CLASSES:
        for title, page in specs:
            links = [("Class guide", f"{other} {cls}", other_page)
                     for other, other_page in specs if other_page != page]
            links.append(("Overview", "All class guides", "class-guides.html"))
            links.append(("Gear", f"{title} {cls} BiS lists", "bis.html"))
            rel[page] = links

    # profession pages
    for _group, entries in PROFESSIONS:
        for title, page in entries:
            key = page.replace(".html", "")
            links = []
            for other_key in PROF_PAIRS.get(key, [])[:3]:
                other_title, other_page = prof_titles[other_key]
                links.append(("Profession", other_title, other_page))
            links.append(("Overview", "All professions", "professions.html"))
            rel[page] = links

    # speed routes: previous/next bracket + comparisons hubward
    routes = LEVELING[0][1]
    comparisons = LEVELING[1][1]
    for i, (title, page) in enumerate(routes):
        links = []
        if i > 0:
            links.append(("Speed route", routes[i - 1][0], routes[i - 1][1]))
        if i + 1 < len(routes):
            links.append(("Speed route", routes[i + 1][0], routes[i + 1][1]))
        links.append(("Method", comparisons[0][0], comparisons[0][1]))
        links.append(("Overview", "Speed leveling", "fast-leveling.html"))
        rel[page] = links

    # comparison pages: the other comparisons + hub
    for title, page in comparisons:
        links = [("Comparison", t, p) for t, p in comparisons if p != page][:3]
        links.append(("Overview", "Speed leveling", "fast-leveling.html"))
        rel[page] = links

    # hub pages: the other hubs
    for page, _title, _kicker in HUBS:
        if page in SKIP:
            continue
        rel[page] = [(k, t, p) for p, t, k in HUBS if p != page]

    return rel


def render(links):
    cards = "\n".join(
        f'    <a class="related-card" href="{href}">'
        f'<span class="related-kicker">{kicker}</span>'
        f'<span class="related-title">{title}</span></a>'
        for kicker, title, href in links)
    return (f"{REL_START}\n"
            f'<section class="related-guides" aria-label="Related guides">\n'
            f'  <h2>Related guides</h2>\n'
            f'  <div class="related-grid">\n{cards}\n  </div>\n'
            f"</section>\n"
            f"{REL_END}")


def stamp(page_path, block):
    html = page_path.read_text()
    if REL_START in html:
        html = re.sub(re.escape(REL_START) + r".*?" + re.escape(REL_END), block, html, flags=re.S)
    else:
        anchor = re.search(r'[ \t]*<footer class="footer">', html)
        if not anchor:
            return False
        html = html[: anchor.start()] + block + "\n" + html[anchor.start():]
    page_path.write_text(html)
    return True


def main():
    relations = build_relations()
    done, missed = 0, []
    for page, links in sorted(relations.items()):
        path = ROOT / "content" / page
        if not path.exists():
            missed.append(f"{page} (file missing)")
            continue
        if stamp(path, render(links)):
            done += 1
        else:
            missed.append(f"{page} (no footer anchor)")
    print(f"Stamped related-guides into {done} pages.")
    for m in missed:
        print("  SKIPPED:", m)


if __name__ == "__main__":
    main()
