#!/usr/bin/env python3
"""Stamp the shared site navigation into every page.

The nav is defined once here (menu data + template) and written into
index.html and every page in content/. Re-running is safe: stamped
blocks are wrapped in sentinel comments and replaced in place.

Usage:  python3 tools/stamp_nav.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

NAV_START = "<!-- sitenav:start (generated by tools/stamp_nav.py — do not edit by hand) -->"
NAV_END = "<!-- sitenav:end -->"
CRUMB_START = "<!-- breadcrumbs:start (generated) -->"
CRUMB_END = "<!-- breadcrumbs:end -->"

# ---------------------------------------------------------------- menu data

CLASSES = [
    ("Warrior", [("Arms", "warrior-arms.html"),
                 ("Fury", "warrior-fury.html"),
                 ("Protection", "warrior-protection.html")]),
    ("Paladin", [("Holy", "paladin-holy.html"),
                 ("Protection", "paladin-protection.html"),
                 ("Retribution", "paladin-retribution.html")]),
    ("Hunter", [("Beast Mastery", "hunter-beast-mastery.html"),
                ("Marksmanship", "hunter-marksmanship.html"),
                ("Survival", "hunter-survival.html")]),
    ("Rogue", [("Assassination", "rogue-assassination.html"),
               ("Combat", "rogue-combat.html"),
               ("Subtlety", "rogue-subtlety.html")]),
    ("Priest", [("Discipline", "priest-discipline.html"),
                ("Holy", "priest-holy.html"),
                ("Shadow", "priest-shadow.html")]),
    ("Death Knight", [("Blood", "death-knight-blood.html"),
                      ("Frost", "death-knight-frost.html"),
                      ("Unholy", "death-knight-unholy.html")]),
    ("Shaman", [("Elemental", "shaman-elemental.html"),
                ("Enhancement", "shaman-enhancement.html"),
                ("Restoration", "shaman-restoration.html")]),
    ("Mage", [("Arcane", "mage-arcane.html"),
              ("Fire", "mage-fire.html"),
              ("Frost", "mage-frost.html")]),
    ("Warlock", [("Affliction", "warlock-affliction.html"),
                 ("Demonology", "warlock-demonology.html"),
                 ("Destruction", "warlock-destruction.html")]),
    ("Druid", [("Balance", "druid-balance.html"),
               ("Feral", "druid-feral.html"),
               ("Restoration", "druid-restoration.html")]),
]

LEVELING = [
    ("Speed Routes", [("Classic 1–60", "fastest-1-60.html"),
                      ("TBC 60–70", "fastest-60-70.html"),
                      ("WotLK 70–80", "fastest-70-80.html"),
                      ("Cata 80–85", "fastest-80-85.html"),
                      ("MoP 85–90", "fastest-85-90.html")]),
    ("Methods & Comparisons", [("Dungeon vs Questing", "dungeon-vs-questing.html"),
                               ("Free vs Premium", "free-vs-premium.html"),
                               ("RestedXP vs Zygor", "restedxp-vs-zygor.html"),
                               ("RestedXP vs Joana", "restedxp-vs-joana.html")]),
]

PROFESSIONS = [
    ("Crafting", [("Alchemy", "alchemy.html"),
                  ("Blacksmithing", "blacksmithing.html"),
                  ("Enchanting", "enchanting.html"),
                  ("Engineering", "engineering.html"),
                  ("Inscription", "inscription.html"),
                  ("Jewelcrafting", "jewelcrafting.html"),
                  ("Leatherworking", "leatherworking.html"),
                  ("Tailoring", "tailoring.html")]),
    ("Gathering", [("Herbalism", "herbalism.html"),
                   ("Mining", "mining.html"),
                   ("Skinning", "skinning.html")]),
    ("Secondary", [("Cooking", "cooking.html"),
                   ("First Aid", "first-aid.html"),
                   ("Fishing", "fishing.html")]),
]

BIS = [
    ("Expansions", [("Classic", "bis.html#classic"),
                    ("TBC", "bis.html#tbc"),
                    ("WotLK", "bis.html#wotlk"),
                    ("Cataclysm", "bis.html#cata"),
                    ("MoP", "bis.html#mop")]),
]

SECTIONS = [
    # (label, hub page, groups, "view all" text)
    ("Classes", "class-guides.html", CLASSES, "View all class guides →"),
    ("Leveling", "fast-leveling.html", LEVELING, "Speed leveling overview →"),
    ("Professions", "professions.html", PROFESSIONS, "All professions →"),
    ("BiS Lists", "bis.html", BIS, "Open the BiS browser →"),
]

PILLS = [
    ("Camelot", "wow-camelot.html", "camelot-pill"),
    ("NEWS", "newcontent.html", "new-pill"),
]

HUB_TITLES = {
    "class-guides.html": "Class Guides",
    "fast-leveling.html": "Speed Leveling",
    "professions.html": "Professions",
    "bis.html": "BiS Lists",
    "wow-camelot.html": "WoW Camelot",
    "newcontent.html": "News",
}

# ------------------------------------------------------------ derived maps


def leaf_titles():
    titles = {}
    for cls, specs in CLASSES:
        for spec, page in specs:
            titles[page] = f"{spec} {cls}"
    for groups in (LEVELING, PROFESSIONS):
        for _, items in groups:
            for label, page in items:
                titles[page] = label
    return titles


def page_section(page):
    """Return (section label, hub page) for a content page, or None."""
    for label, hub, groups, _ in SECTIONS:
        if page == hub:
            return label, hub
        for _, items in groups:
            if page in (p.split("#")[0] for _, p in items):
                return label, hub
    return None


# ------------------------------------------------------------ nav rendering


def render_groups(groups, prefix, current):
    out = []
    for title, items in groups:
        links = []
        for label, page in items:
            cur = ' aria-current="page"' if page == current else ""
            links.append(f'            <a href="{prefix}{page}"{cur}>{label}</a>')
        out.append(
            '          <div class="menu-group">\n'
            f'            <span class="menu-group-title">{title}</span>\n'
            + "\n".join(links) + "\n"
            "          </div>"
        )
    return "\n".join(out)


def render_nav(prefix, assets, home, current):
    section = page_section(current) if current else None
    items = []
    for label, hub, groups, cta in SECTIONS:
        active = " active" if section and section[0] == label else ""
        items.append(f"""      <li class="nav-item has-dropdown">
        <div class="nav-item-row">
          <a href="{prefix}{hub}" class="nav-link{active}">{label}<span class="caret" aria-hidden="true">▾</span></a>
          <button class="submenu-toggle" aria-expanded="false" aria-label="Open {label} menu">▾</button>
        </div>
        <div class="dropdown">
          <div class="dropdown-inner">
{render_groups(groups, prefix, current)}
          </div>
          <div class="dropdown-cta"><a href="{prefix}{hub}">{cta}</a></div>
        </div>
      </li>""")
    for label, page, pill in PILLS:
        active = " active" if page == current else ""
        items.append(f'      <li class="nav-item">\n'
                     f'        <a href="{prefix}{page}" class="nav-link {pill}{active}">{label}</a>\n'
                     f'      </li>')
    items_html = "\n".join(items)
    return f"""{NAV_START}
<nav class="nav">
  <div class="nav-container">
    <a href="{home}" class="logo-link"><img src="{assets}boostyou.png" alt="Boostyou.ai logo" /></a>
    <button class="mobile-toggle" onclick="toggleMobileMenu()" aria-label="Toggle menu" aria-expanded="false" aria-controls="navMenu">☰</button>
    <ul class="nav-menu" id="navMenu">
{items_html}
    </ul>
  </div>
</nav>
{NAV_END}"""


def render_breadcrumbs(home, current):
    title = HUB_TITLES.get(current) or leaf_titles().get(current)
    if not title:
        return None
    parts = [f'<a href="{home}">Home</a>']
    section = page_section(current)
    if section and current != section[1]:
        label, hub = section
        parts.append(f'<a href="{hub}">{label}</a>')
    parts.append(f'<span class="crumb-current">{title}</span>')
    sep = '<span class="crumb-sep">›</span>'
    return (f"{CRUMB_START}\n"
            f'<div class="breadcrumbs">{sep.join(parts)}</div>\n'
            f"{CRUMB_END}")


# ------------------------------------------------------------ file stamping


def stamp(path, prefix, assets, home, current):
    html = path.read_text(encoding="utf-8")
    nav = render_nav(prefix, assets, home, current)

    # Replace a previously stamped nav, else the page's original <nav> block
    sentinel = re.compile(re.escape(NAV_START) + r".*?" + re.escape(NAV_END), re.S)
    legacy = re.compile(r'<nav class="nav">.*?</nav>', re.S)
    if sentinel.search(html):
        html = sentinel.sub(lambda _: nav, html, count=1)
    elif legacy.search(html):
        html = legacy.sub(lambda _: nav, html, count=1)
    else:
        html = re.sub(r"(<body[^>]*>)", lambda m: m.group(1) + "\n" + nav, html, count=1)

    # Breadcrumbs directly below the nav (content pages only)
    crumb_re = re.compile(re.escape(CRUMB_START) + r".*?" + re.escape(CRUMB_END) + r"\n?", re.S)
    html = crumb_re.sub("", html)
    if current:
        crumbs = render_breadcrumbs(home, current)
        if crumbs:
            html = html.replace(NAV_END, NAV_END + "\n" + crumbs, 1)

    # Shared stylesheet and script, once per page, after the inline styles
    if f'{assets}nav.css' not in html:
        html = html.replace("</head>", f'<link rel="stylesheet" href="{assets}nav.css" />\n</head>', 1)
    if f'{assets}nav.js' not in html:
        html = html.replace("</head>", f'<script src="{assets}nav.js" defer></script>\n</head>', 1)

    path.write_text(html, encoding="utf-8")


def main():
    index = ROOT / "index.html"
    stamp(index, prefix="content/", assets="assets/", home="./", current=None)
    count = 1
    for path in sorted((ROOT / "content").glob("*.html")):
        stamp(path, prefix="", assets="../assets/", home="../", current=path.name)
        count += 1
    print(f"Stamped nav into {count} pages.")


if __name__ == "__main__":
    sys.exit(main())
